source 'https://rubygems.org'
gem 'github-pages'
gem 'jekyll-paginate'
gem 'jekyll-sitemap'
gem 'jekyll-import'
gem 'wdm'
gem 'public_suffix'
gem 'breakpoint'
gem 'octopress-autoprefixer'
gem 'guard'
gem 'guard-jekyll-plus'
gem 'guard-livereload'
gem 'rubyzip', '>= 1.3.0'
gem 'nokogiri', '>= 1.10.8'
gem 'mini_magick', '>= 4.9.4'
gem 'rack', '>= 1.6.12'

group :jekyll_plugins do
  gem 'jekyll-picture-tag'
	gem 'jekyll-admin'
end
