audit_header: false
title: Phoenix Real Estate Video Blog with Sam Levy
description: Our mission at The Brokery is to be your best resource for Phoenix real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Brokery, your professional Phoenix Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Sam Levy
  title:
  license_number:
  about_markdown: |
    I see myself as a public servant. Being able to help people with their real estate needs is a passion of mine! When we work together, I can promise that I will do everything possible to make the purchase or sale of your home as easy and pleasant as possible. When problems arise, we will make sure they get taken care of. When you have a question or concern, call me and I'll make sure you feel at ease. I look at my clients as family, and I would never treat a family member with anything but the absolute best service.

    Being a native Phoenician, I've seen different parts of the city grow and develop. When I was growing up in Central Phoenix, 7th Street, or "Restaurant Row" as it's now called, had almost no restaurants! Seeing growth like this has allowed me to develop a keen eye for up and coming areas. Furthermore, being born and raised here has allotted me the opportunity to know every part of the city like the back of my hand! I often know good schools, and ALWAYS know good restaurants in certain areas (eating is my favorite hobby).
  brand: The Brokery
  brokerage:
  market: Phoenix
  address: 4546 N 40th St, Phoenix AZ 85018
  phone: 602-501-9352
  phone_type:
  phone2:
  phone2_type:
  email: sam@thebrokery.com
  url: https://samlevyhomes.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.centralphoenixappraisal.com/
  second_CTA_text: Home Search
  second_CTA_URL: https://samlevyhomes.com/advanced-search/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Phoenix Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://www.centralphoenixappraisal.com/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Phoenix Home?"
    CTA_text2: "Search the entire MLS for your Phoenix home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://samlevyhomes.com/advanced-search/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: true
  facebook_url: https://www.facebook.com/SamLevyRealtor/
  linkedin_url: https://www.linkedin.com/in/sam-levy-67353857
  youtube_url:
  twitter_url:
  instagram_url: https://www.instagram.com/samlevyrealtor/
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/samlevy2045/
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Phoenix Real Estate Podcast with Sam Levy'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Phoenix Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from The Brokery - your professional Phoenix Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Phoenix, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Sam Levy'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Phoenix Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#4ab9d4'
  theme_color: '#000000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#4ab9d4'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
